# Even Fibonacci numbers
# Problem 2
# Each new term in the Fibonacci sequence is generated by adding the previous two terms.
# By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million,
# find the sum of the even-valued terms.

function main(n::Int)
    fibonacci = [1,2]
    for x in 3:100000
        v = fibonacci[x-2]+fibonacci[x-1]
        if v > n
            break
        end
        push!(fibonacci, v)
    end
    sum(filter(iseven, fibonacci))
end

 @time println(main(4000000))
